#!/usr/bin/env python3
"""Load an official local VBIOREG100 SHP and derive postcode overlaps."""

from __future__ import annotations

import argparse
import csv
import io
import json
import os
import re
import subprocess
import sys
from pathlib import Path
import geopandas as gpd

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from common import (  # noqa: E402
    LOG,
    DatabaseConfig,
    configure_logging,
    finish_data_load,
    register_source,
    run_psql,
    start_data_load,
)


DATASET_URL = (
    "https://discover.data.vic.gov.au/dataset/"
    "victorian-bioregions-mapped-at-1-100000-version-3-0-may2004"
)
EXPECTED_REGION_COUNT = 28
SOURCE = {
    "name": "DEECA Victorian Bioregions 1:100,000",
    "provider": "Victorian Department of Energy, Environment and Climate Action",
    "url": DATASET_URL,
    "licence": "Creative Commons Attribution 4.0 International (CC BY 4.0)",
    "version": "VBIOREG100 version 3.0 (May 2004)",
}
CODE_RE = re.compile(r"^[A-Za-z0-9]{2,10}$")


def shapefile_to_geojson(path: Path) -> dict:
    if path.suffix.casefold() != ".shp":
        raise ValueError("Victorian Bioregion input must be the downloaded .shp file")
    missing = [str(path.with_suffix(ext)) for ext in (".shp", ".dbf", ".shx", ".prj")
               if not path.with_suffix(ext).is_file()]
    if missing:
        raise FileNotFoundError("missing required shapefile components: " + ", ".join(missing))

    try:
        gdf = gpd.read_file(path)
        gdf = gdf.to_crs(epsg=4326)
        gdf = gdf[["BIOREGCODE", "BIOREGION", "geometry"]]
    except Exception as error:
        raise RuntimeError(f"shapefile conversion failed: {error}") from error

    return json.loads(gdf.to_json())


def _coordinate_pairs(value: object):
    if isinstance(value, list) and len(value) >= 2 and all(
        isinstance(item, (int, float)) for item in value[:2]
    ):
        yield float(value[0]), float(value[1])
        return
    if isinstance(value, list):
        for item in value:
            yield from _coordinate_pairs(item)


def read_and_validate(
    source: Path | dict,
    expected_count: int,
) -> list[tuple[str, str, dict]]:
    document = shapefile_to_geojson(source) if isinstance(source, Path) else source
    if document.get("type") != "FeatureCollection":
        raise ValueError("input must be a GeoJSON FeatureCollection")
    if document.get("exceededTransferLimit"):
        raise ValueError("source response exceeded the service transfer limit")

    rows: list[tuple[str, str, dict]] = []
    codes: set[str] = set()
    names: set[str] = set()
    for index, feature in enumerate(document.get("features", []), start=1):
        properties = feature.get("properties") or {}
        code = str(properties.get("BIOREGCODE", "")).strip()
        name = str(properties.get("BIOREGION", "")).strip()
        geometry = feature.get("geometry") or {}
        if not CODE_RE.fullmatch(code):
            raise ValueError(f"feature {index} has invalid Victorian Bioregion code {code!r}")
        if not name:
            raise ValueError(f"Victorian Bioregion {code} has no name")
        if geometry.get("type") not in {"Polygon", "MultiPolygon"}:
            raise ValueError(f"Victorian Bioregion {code} is not polygon geometry")
        pairs = list(_coordinate_pairs(geometry.get("coordinates")))
        if not pairs:
            raise ValueError(f"Victorian Bioregion {code} has empty geometry")
        if any(not (65 <= x <= 175 and -60 <= y <= -5) for x, y in pairs):
            raise ValueError(
                f"Victorian Bioregion {code} coordinates are not plausible EPSG:4326"
            )
        codes.add(code)
        names.add(name)
        rows.append((code, name, geometry))

    pairs = {(code, name) for code, name, _ in rows}
    if len(codes) != len(pairs) or len(names) != len(pairs):
        raise ValueError("Victorian Bioregion code/name mapping is not one-to-one")
    if len(pairs) != expected_count:
        raise ValueError(
            f"expected {expected_count} Victorian Bioregions, received {len(pairs)} "
            f"across {len(rows)} polygon fragments"
        )
    return rows


def _copy_csv(rows: list[tuple[str, str, dict]]) -> str:
    output = io.StringIO()
    writer = csv.writer(output, lineterminator="\n")
    for code, name, geometry in rows:
        writer.writerow((code, name, json.dumps(geometry, separators=(",", ":"))))
    return output.getvalue()


def load_rows(
    config: DatabaseConfig,
    source_id: int,
    rows: list[tuple[str, str, dict]],
) -> tuple[int, int, int]:
    region_count = len({(code, name) for code, name, _ in rows})
    sql = rf"""
BEGIN;
CREATE TEMP TABLE bioregion_stage (
    fragment_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    region_code text NOT NULL,
    region_name text NOT NULL,
    geometry_json jsonb NOT NULL
) ON COMMIT DROP;
\copy bioregion_stage (region_code, region_name, geometry_json) FROM STDIN WITH (FORMAT csv)
{_copy_csv(rows)}\.

CREATE TEMP TABLE bioregion_clean ON COMMIT DROP AS
SELECT region_code,
       region_name,
       ST_UnaryUnion(ST_Collect(source_geometry)) AS source_geometry,
       ST_Multi(
           ST_CollectionExtract(
               ST_MakeValid(ST_UnaryUnion(ST_Collect(source_geometry))), 3
           )
       ) AS geometry
FROM (
    SELECT region_code,
           region_name,
           ST_SetSRID(ST_GeomFromGeoJSON(geometry_json::text), 4326)
               AS source_geometry
    FROM bioregion_stage
        ) parsed
GROUP BY region_code, region_name
;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM bioregion_clean
        WHERE region_code !~ '^[A-Za-z0-9]{{2,10}}$'
           OR region_name = ''
           OR geometry IS NULL
           OR ST_IsEmpty(geometry)
           OR NOT ST_IsValid(geometry)
           OR GeometryType(geometry) <> 'MULTIPOLYGON'
           OR ST_SRID(geometry) <> 4326
    ) THEN
        RAISE EXCEPTION 'Victorian Bioregion staging validation failed';
    END IF;
    IF NOT EXISTS (SELECT 1 FROM postcode) THEN
        RAISE EXCEPTION 'postcode ingestion must run before bioregion ingestion';
    END IF;
END $$;

INSERT INTO bioregion (source_id, bioregion_name, geometry)
SELECT {source_id}, region_name,
       ST_Multi(geometry)::geometry(MultiPolygon, 4326)
FROM bioregion_clean
ON CONFLICT (source_id, bioregion_name) DO UPDATE SET
    geometry = EXCLUDED.geometry;

DO $$
BEGIN
    IF (SELECT count(*) FROM bioregion WHERE source_id = {source_id}) <> {region_count} THEN
        RAISE EXCEPTION 'database/source region count differs from staged row count';
    END IF;
END $$;

CREATE TEMP TABLE postcode_bioregion_stage ON COMMIT DROP AS
WITH transformed AS (
    SELECT p.postcode,
           ST_Transform(p.geometry, 3577) AS postcode_geometry,
           b.bioregion_id,
           ST_Transform(b.geometry, 3577) AS bioregion_geometry
    FROM postcode p
    JOIN bioregion b
      ON b.source_id = {source_id}
     AND ST_Intersects(p.geometry, b.geometry)
), intersections AS (
    SELECT postcode, bioregion_id, postcode_geometry,
           ST_Intersection(postcode_geometry, bioregion_geometry) AS overlap_geometry
    FROM transformed
)
SELECT postcode,
       bioregion_id,
       round((100 * ST_Area(overlap_geometry)
             / NULLIF(ST_Area(postcode_geometry), 0))::numeric, 2)::numeric(5, 2)
           AS overlap_percent
FROM intersections
WHERE NOT ST_IsEmpty(overlap_geometry)
  AND ST_Area(overlap_geometry) > 0;

ALTER TABLE postcode_bioregion_stage
    ADD PRIMARY KEY (postcode, bioregion_id);

DO $$
DECLARE
    postcode_count integer := (SELECT count(*) FROM postcode);
    relationship_count integer := (SELECT count(*) FROM postcode_bioregion_stage);
BEGIN
    IF relationship_count < postcode_count OR relationship_count > postcode_count * 10 THEN
        RAISE EXCEPTION 'implausible postcode-bioregion relationship count: %', relationship_count;
    END IF;
    IF EXISTS (
        SELECT 1 FROM postcode p
        WHERE NOT EXISTS (
            SELECT 1 FROM postcode_bioregion_stage r WHERE r.postcode = p.postcode
        )
    ) THEN
        RAISE EXCEPTION 'one or more postcodes have no positive-area bioregion intersection';
    END IF;
END $$;

DELETE FROM postcode_bioregion relationship
USING bioregion b
WHERE relationship.bioregion_id = b.bioregion_id
  AND b.source_id = {source_id};

INSERT INTO postcode_bioregion (postcode, bioregion_id, overlap_percent)
SELECT postcode, bioregion_id, overlap_percent
FROM postcode_bioregion_stage;

SELECT (SELECT count(*) FROM bioregion WHERE source_id = {source_id})
       || '|' ||
       (SELECT count(*) FROM postcode_bioregion relationship
        JOIN bioregion b USING (bioregion_id)
        WHERE b.source_id = {source_id})
       || '|' ||
       (SELECT count(*) FROM bioregion_clean WHERE NOT ST_IsValid(source_geometry));
COMMIT;
"""
    result = run_psql(config, sql)
    region_count, relationship_count, repaired_count = result.splitlines()[-1].split("|")
    return int(region_count), int(relationship_count), int(repaired_count)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", type=Path, required=True, help="official VBIOREG100 .shp")
    parser.add_argument(
        "--expected-count", type=int, default=EXPECTED_REGION_COUNT,
        help="version-specific row-count guard",
    )
    parser.add_argument("--verbose", action="store_true")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    configure_logging(args.verbose)
    config = DatabaseConfig.from_environment()
    source_id = register_source(config, SOURCE)
    load_id = start_data_load(
        config, source_id, f"Victorian Bioregion load requested from {args.input.name}"
    )
    received: int | None = None
    try:
        rows = read_and_validate(args.input, args.expected_count)
        received = len(rows)
        accepted, relationship_count, repaired_count = load_rows(config, source_id, rows)
        finish_data_load(
            config, load_id, status="complete", received=received,
            accepted=accepted, rejected=0,
            notes=(f"Loaded {accepted} Victorian Bioregions from {args.input.name}; repaired "
                   f"{repaired_count} invalid source geometries with ST_MakeValid; derived "
                   f"{relationship_count} positive-area postcode relationships in EPSG:3577"),
        )
        LOG.info(
            "Load %s complete: regions=%s repaired=%s relationships=%s rejected=0",
            load_id, accepted, repaired_count, relationship_count,
        )
        return 0
    except Exception as error:
        LOG.exception("Victorian Bioregion load %s failed", load_id)
        finish_data_load(
            config, load_id, status="failed", received=received,
            accepted=0 if received is not None else None, rejected=received,
            notes=f"Failed: {error}",
        )
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
