BEGIN;

CREATE EXTENSION IF NOT EXISTS postgis;

CREATE TABLE source (
    source_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_name text NOT NULL,
    provider text,
    url text,
    licence text,
    version text,
    UNIQUE NULLS NOT DISTINCT (source_name, version)
);

CREATE TABLE data_load (
    load_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id bigint NOT NULL REFERENCES source (source_id),
    started_at timestamptz NOT NULL DEFAULT now(),
    completed_at timestamptz,
    status text NOT NULL,
    rows_received integer CHECK (rows_received >= 0),
    rows_accepted integer CHECK (rows_accepted >= 0),
    rows_rejected integer CHECK (rows_rejected >= 0),
    notes text,
    CHECK (completed_at IS NULL OR completed_at >= started_at),
    CHECK (
        rows_received IS NULL
        OR rows_accepted IS NULL
        OR rows_rejected IS NULL
        OR rows_accepted + rows_rejected <= rows_received
    )
);

CREATE TABLE postcode (
    postcode text PRIMARY KEY CHECK (postcode ~ '^[0-9]{4}$'),
    geometry geometry(MultiPolygon, 4326) NOT NULL,
    source_id bigint NOT NULL REFERENCES source (source_id)
);

CREATE TABLE bioregion (
    bioregion_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id bigint NOT NULL REFERENCES source (source_id),
    bioregion_name text NOT NULL,
    geometry geometry(MultiPolygon, 4326) NOT NULL,
    UNIQUE (source_id, bioregion_name)
);

CREATE TABLE postcode_bioregion (
    postcode text NOT NULL REFERENCES postcode (postcode),
    bioregion_id bigint NOT NULL REFERENCES bioregion (bioregion_id),
    overlap_percent numeric(5, 2) NOT NULL CHECK (overlap_percent BETWEEN 0 AND 100),
    PRIMARY KEY (postcode, bioregion_id)
);

CREATE TABLE evc_class (
    evc_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id bigint NOT NULL REFERENCES source (source_id),
    evc_code text NOT NULL,
    evc_name text NOT NULL,
    conservation_status text,
    UNIQUE (source_id, evc_code)
);

COMMENT ON TABLE evc_class IS
    'Vegetation-community context only; not evidence that an individual historical plant species was present or lost.';

CREATE TABLE postcode_evc_context (
    postcode_evc_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    postcode text NOT NULL REFERENCES postcode (postcode),
    evc_id bigint NOT NULL REFERENCES evc_class (evc_id),
    source_id bigint NOT NULL REFERENCES source (source_id),
    reference_year smallint NOT NULL CHECK (reference_year > 0),
    overlap_percent numeric(5, 2) NOT NULL CHECK (overlap_percent BETWEEN 0 AND 100),
    UNIQUE (postcode, evc_id, source_id, reference_year)
);

CREATE TABLE fauna_species (
    fauna_species_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scientific_name text NOT NULL UNIQUE,
    common_name text,
    taxon_group text
);

CREATE TABLE fauna_occurrence_summary (
    fauna_occurrence_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    postcode text NOT NULL REFERENCES postcode (postcode),
    fauna_species_id bigint NOT NULL REFERENCES fauna_species (fauna_species_id),
    source_id bigint NOT NULL REFERENCES source (source_id),
    record_count integer NOT NULL CHECK (record_count >= 0),
    latest_record_date date,
    UNIQUE (postcode, fauna_species_id, source_id)
);

COMMENT ON COLUMN fauna_occurrence_summary.record_count IS
    'Occurrence record count reflects observation/monitoring effort, not abundance; no records do not prove absence.';

CREATE TABLE fauna_trait (
    fauna_trait_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fauna_species_id bigint NOT NULL REFERENCES fauna_species (fauna_species_id),
    source_id bigint NOT NULL REFERENCES source (source_id),
    trait_name text NOT NULL,
    trait_value text NOT NULL
);

CREATE TABLE fauna_guild (
    fauna_guild_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_name text NOT NULL UNIQUE,
    description text
);

CREATE TABLE fauna_guild_membership (
    fauna_species_id bigint NOT NULL REFERENCES fauna_species (fauna_species_id),
    fauna_guild_id bigint NOT NULL REFERENCES fauna_guild (fauna_guild_id),
    membership_role text NOT NULL CHECK (membership_role IN ('primary', 'co_dominant', 'secondary')),
    PRIMARY KEY (fauna_species_id, fauna_guild_id)
);

CREATE TABLE fauna_garden_relevance (
    fauna_species_id bigint PRIMARY KEY REFERENCES fauna_species (fauna_species_id),
    source_id bigint NOT NULL REFERENCES source (source_id),
    relevance_status text NOT NULL CHECK (
        relevance_status IN ('candidate', 'context_only', 'excluded_driver', 'pending_review')
    ),
    rationale text
);

CREATE TABLE habitat_requirement (
    habitat_requirement_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requirement_name text NOT NULL UNIQUE,
    description text
);

CREATE TABLE guild_habitat_rule (
    guild_habitat_rule_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fauna_guild_id bigint NOT NULL REFERENCES fauna_guild (fauna_guild_id),
    habitat_requirement_id bigint NOT NULL REFERENCES habitat_requirement (habitat_requirement_id),
    source_id bigint NOT NULL REFERENCES source (source_id),
    status text NOT NULL CHECK (
        status IN ('validated_for_coarse_use', 'conditional', 'unsupported', 'insufficient_evidence')
    ),
    evidence text NOT NULL
);

CREATE TABLE plant_species (
    plant_species_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scientific_name text NOT NULL UNIQUE,
    common_name text,
    native_status text
);

CREATE TABLE plant_trait (
    plant_trait_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plant_species_id bigint NOT NULL REFERENCES plant_species (plant_species_id),
    source_id bigint NOT NULL REFERENCES source (source_id),
    trait_name text NOT NULL,
    trait_value text NOT NULL
);

COMMENT ON TABLE plant_trait IS
    'Record-level traits; multiple and conflicting values for the same plant and trait name are preserved.';

CREATE TABLE plant_resource_evidence (
    plant_resource_evidence_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plant_species_id bigint NOT NULL REFERENCES plant_species (plant_species_id),
    habitat_requirement_id bigint NOT NULL REFERENCES habitat_requirement (habitat_requirement_id),
    source_id bigint NOT NULL REFERENCES source (source_id),
    evidence_summary text NOT NULL
);

COMMENT ON TABLE plant_resource_evidence IS
    'Documents habitat/resource contributions; it must not be interpreted as a promise to attract a fauna species.';

CREATE TABLE local_plant_suitability (
    local_suitability_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plant_species_id bigint NOT NULL REFERENCES plant_species (plant_species_id),
    bioregion_id bigint NOT NULL REFERENCES bioregion (bioregion_id),
    source_id bigint NOT NULL REFERENCES source (source_id),
    suitability_status text NOT NULL,
    evidence_summary text NOT NULL
);

COMMENT ON TABLE local_plant_suitability IS
    'Regional suitability evidence only; it does not establish parcel-level suitability.';

CREATE INDEX data_load_source_idx ON data_load (source_id);
CREATE INDEX postcode_source_idx ON postcode (source_id);
CREATE INDEX postcode_geometry_gix ON postcode USING gist (geometry);
CREATE INDEX bioregion_source_idx ON bioregion (source_id);
CREATE INDEX bioregion_geometry_gix ON bioregion USING gist (geometry);
CREATE INDEX postcode_bioregion_bioregion_idx ON postcode_bioregion (bioregion_id, postcode);
CREATE INDEX evc_class_source_idx ON evc_class (source_id);
CREATE INDEX postcode_evc_context_postcode_idx ON postcode_evc_context (postcode);
CREATE INDEX postcode_evc_context_evc_idx ON postcode_evc_context (evc_id);
CREATE INDEX postcode_evc_context_source_idx ON postcode_evc_context (source_id);
CREATE INDEX fauna_occurrence_postcode_idx ON fauna_occurrence_summary (postcode);
CREATE INDEX fauna_occurrence_species_idx ON fauna_occurrence_summary (fauna_species_id);
CREATE INDEX fauna_occurrence_source_idx ON fauna_occurrence_summary (source_id);
CREATE INDEX fauna_trait_species_name_idx ON fauna_trait (fauna_species_id, trait_name);
CREATE INDEX fauna_trait_source_idx ON fauna_trait (source_id);
CREATE INDEX fauna_guild_membership_guild_idx ON fauna_guild_membership (fauna_guild_id, fauna_species_id);
CREATE INDEX fauna_garden_relevance_source_idx ON fauna_garden_relevance (source_id);
CREATE INDEX guild_habitat_rule_guild_idx ON guild_habitat_rule (fauna_guild_id);
CREATE INDEX guild_habitat_rule_requirement_idx ON guild_habitat_rule (habitat_requirement_id);
CREATE INDEX guild_habitat_rule_source_idx ON guild_habitat_rule (source_id);
CREATE INDEX plant_trait_species_name_idx ON plant_trait (plant_species_id, trait_name);
CREATE INDEX plant_trait_source_idx ON plant_trait (source_id);
CREATE INDEX plant_resource_evidence_plant_idx ON plant_resource_evidence (plant_species_id);
CREATE INDEX plant_resource_evidence_requirement_idx ON plant_resource_evidence (habitat_requirement_id);
CREATE INDEX plant_resource_evidence_source_idx ON plant_resource_evidence (source_id);
CREATE INDEX local_plant_suitability_plant_idx ON local_plant_suitability (plant_species_id);
CREATE INDEX local_plant_suitability_bioregion_idx ON local_plant_suitability (bioregion_id, plant_species_id);
CREATE INDEX local_plant_suitability_source_idx ON local_plant_suitability (source_id);

COMMIT;
