BEGIN;

-- The approved v1 schema has a postcode/fauna occurrence summary but no
-- equivalent relationship for documented flora occurrences. VBA occurrence
-- cannot be stored honestly as a trait, suitability conclusion, or resource
-- assertion, so this is the smallest additive relationship required.
CREATE TABLE plant_occurrence_summary (
    plant_occurrence_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    postcode text NOT NULL REFERENCES postcode (postcode),
    plant_species_id bigint NOT NULL REFERENCES plant_species (plant_species_id),
    source_id bigint NOT NULL REFERENCES source (source_id),
    source_taxon_id text NOT NULL,
    record_count bigint NOT NULL CHECK (record_count >= 0),
    latest_record_date date,
    period_start date,
    period_end date,
    CONSTRAINT plant_occurrence_summary_period_check
        CHECK (period_end IS NULL OR period_start IS NULL OR period_end >= period_start),
    CONSTRAINT plant_occurrence_summary_window_uq
        UNIQUE NULLS NOT DISTINCT (
            postcode, plant_species_id, source_id, source_taxon_id,
            period_start, period_end
        )
);

COMMENT ON TABLE plant_occurrence_summary IS
    'Area-level documented flora occurrence summaries; not planting suitability or a recommendation.';
COMMENT ON COLUMN plant_occurrence_summary.record_count IS
    'VBA observation-record count, not abundance; no records do not prove absence.';
COMMENT ON COLUMN plant_occurrence_summary.source_taxon_id IS
    'Taxon identifier supplied by the occurrence source; not a cross-source accepted-name identifier.';

CREATE INDEX plant_occurrence_postcode_idx
    ON plant_occurrence_summary (postcode);
CREATE INDEX plant_occurrence_species_idx
    ON plant_occurrence_summary (plant_species_id);
CREATE INDEX plant_occurrence_source_idx
    ON plant_occurrence_summary (source_id);

COMMIT;
